FROM python:3.11-slim

ENV PYTHONBUFFERED=1

WORKDIR /app

COPY requirements.txt requirements.txt


# Instalar dependências do sistema (incluindo as do WeasyPrint)
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    gcc \
    libcairo2 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libgdk-pixbuf-2.0-0 \
    libffi-dev \
    shared-mime-info \
    && rm -rf /var/lib/apt/lists/*


RUN apt-get update && apt-get install -y \
    tesseract-ocr \
    tesseract-ocr-por \
    libtesseract-dev \
    poppler-utils \
    && rm -rf /var/lib/apt/lists/*


    
# Instala dependências para o psycopg2
RUN apt-get update && apt-get install -y libpq-dev gcc
RUN python -m pip install --upgrade pip
RUN python -m pip install --no-cache-dir -r requirements.txt

COPY . . 

EXPOSE 5000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
